#ifndef VTKOCC_IMPORT_QT_H
#define VTKOCC_IMPORT_QT_H

#include <QtCore/QObject>
#include <QtCore/QDebug>
#include <QtCore/QTimer>
#include <QtCore/QTime>
#include <QtCore/QMap>
#include <QtCore/QVector>
#include <QtCore/QList>
#include <QtCore/QString>
#include <QtCore/QFile>
#include <QtCore/QResource>
#include <QtCore/QRunnable>
#include <QtCore/QThread>
#include <QtCore/QThreadPool>
#include <QtCore/QJsonObject>
#include <QtCore/QMutex>
#include <QtCore/QWaitCondition>
#include <QtCore/QFileSystemWatcher>
#include <QtGui/QFont>
#include <QtGui/QIcon>
#include <QtGui/QFontDatabase>
#include <QtGui/QPainter>
#include <QtGui/QBitmap>
#include <QtGui/QResizeEvent>
#include <QtWidgets/QApplication>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QWidget>
#include <QtWidgets/QDialog>
#include <QtWidgets/QDesktopWidget>
#include <QtWidgets/QOpenGLWidget>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLayout>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QBoxLayout>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QScrollArea>
#include <QtWidgets/QTextBrowser>
#include <QtWidgets/qfiledialog.h>
#include <QtWidgets/qstyleoption.h>
#include <QtWidgets/qstylepainter.h>
#include <QtScript/QScriptEngine>
#include <QtScript/QScriptClass>
#include <QtScript/QScriptContext>
#include <QtScript/QScriptValue>
#include <QtScript/QScriptClass>
#include <QtScript/QScriptValueIterator>

#endif //VTKOCC_IMPORT_QT_H
